### ISSUE TITLE
[Feature Request] Show furigana/translation after mistake

### ISSUE THREAD

**Issue by krzysztof-krzeszowski** [baileysnyder/japanese-conjugation#17]
First of all thank you for an amazing tool :) I'd like to suggest an option to turn on furigana and/or translation when one makes a mistake given furigana and/or translation is set to be not shown during the quiz. In this way one can not only learn the conjugation but also learn the reading and translation of verbs and adjectives.

**Comment by baileysnyder** [comment]
Thanks, glad you like it :D

While I could see people using this, I feel like this app isn't the best way to learn readings and translations so it wouldn't be best to encourage. The current app gives you groups of words based on how they're translated, but the user doesn't have control over the specific words that appear if they want to learn their reading/translation. Then the app's English translations were made to be as short and concise as possible, not necessarily descriptive. I also tend to be against traditional flashcards with a single Japanese word on the front and an English translation on the back, although that's just my opinion. Overall, I think conjugation is this app's strong suit, while if someone wanted a flashcard-y way to learn translations and readings Anki would be much better.

Another issue, although probably solvable, is that I can't think of a 100% clean way to add this to the options. All of the options are on by default, but if this was called "Always show furigana and translation after a mistake" it would be the first option I want to default to off. Then it takes a second to think through how you want this option to be set in relation to the regular show furigana and show translation options.

Tbh I may be overly afraid of things that add ""complexity"" for the user or change in scope lol. Still, this was good to start thinking through so thanks for the suggestion.

**Comment by baileysnyder** [comment]
The current setup is pretty basic: If you miss a question the app will try to show it again in 3 rounds. Then once you get it right the question is given a lower probability to appear than any other question. If you visit the options menu at all the probabilities are reset.

I agree that if you miss one, it feels like it should be more likely to reappear than one you got right on the first try. I'm not sure I'd do it by verb/adjective specifically because I think on average missing, for example, 食べなかった would be poorly corelated with missing 食べます just because they have the same stem. But doing it for a specific stem+conjugation question makes sense to me.

I'm also not sure if I'd want to give mistakes a higher probability to appear than unseen questions. Since there aren't that many words in total, and assuming the user has selected options to limit the number of words in the rotation, it will probably be better for them to see the remaining unanswered questions than to re-answer a question they had trouble with a few minutes ago.

So I'm thinking the right probability order is: very recently missed -> unseen -> previously missed -> previously correct on first try. Sometime this week I'll try to set this up and make sure it only resets when you *change* a conjugation option in the options menu. In the future I might want to store the probabilities globally so they don't ever reset, and then store them in the browser's local storage like you suggested, but that's gonna be hefty so I'll go a step at a time lol.

**Comment by baileysnyder** [comment]
I made some progress on the probability changes! It probably won't be very noticeable in the app, but I was able to do the ordering I mentioned. I opened a separate issue to do the global probability thing we talked about. Tbh it's gonna be on the back burner for a bit because it's going to be a decent amount of work and I still need to think through exactly how to approach it.

The reason I don't show everything on the results screen is because currently it would change the height of everything, and I like how the transition from the question to the results screen is seamless. I could fix this by making everything a set height so the furigana and translation don't change it, but I avoided that since I didn't like all the extra white space when on the question screen. I'm sure this can be solved somehow, but it still doesn't take into account people who check those hide settings just because they don't like the extra clutter and want to focus only on what they care about.

My answer isn't a hard no though so I'm going to keep this issue open. Just a soft no for the app in its current state.

**Comment by vinceau** [comment]
I personally only care about hiding the translation, but I only also added hiding furigana too after reading this thread. I don't think splitting that "Show English translations" option is really necessary.

Consider the target user who will have that option selected.

* People who already know the English translations will have it turned off, and even if it shows upon result, they already know it so it doesn't affect them. Plus they would only see it for like 0.5 second anyways before they hit the next word. Basically no net negative.
* People who don't already know the English translation have a chance to practice their vocab and memorisation. Net positive.

I think splitting the option is like complicating things more than necessary, for an feature that IMO has no negative impact on either user.

If you'd like, I can update my PR to not change the furigana behaviour and only always show English translation after answering.

**Comment by baileysnyder** [comment]
@vinceau I actually agree for the most part. I'd agree the group of people that want to always hide the translation seem like the smallest out of the proposed 3, and then the number of people in that group that would hate the translation still showing up after answering seems even smaller.

My biggest issue with the current PR is that the setting doesn't clearly describe what it does. "Show English translations" still sounds like it would completely show/hide the translations, so it's not obvious to a new user that showing the translation after answering is a feature. We could change the text but I can't think of anything that sits 100% right with me. "Show English translation before answering", "Show English translation during question", I dunno. Preferably it'd be worded so the option defaults to being checked, since all of the other options default to being checked.

On the one hand it seems like a nuclear option to add 2 new radio buttons like I suggested, but on the other hand it feels the easiest to read to me, and it keeps the option for that <1% of users who just want to hide everything. I'm not asking you to code that solution btw since it'd be a whole thing - I could work on it sometime this week. For now I'm still letting the ideas marinate a bit.

**Comment by baileysnyder** [comment]
I went ahead with the radio option route - should be live on the site. For now I've decided against the similar option for furigana, so I'm going to mark this issue as closed. Thanks for all the help guys @vinceau @krzysztof-krzeszowski
