### ISSUE TITLE
More conjugation forms?

### ISSUE THREAD

**Issue by domfarolino** [baileysnyder/japanese-conjugation#22]
Has any thought been put into adding other conjugation forms to the web app, like potential form, 〜たい form, and so on?

**Comment by baileysnyder** [comment]
There was discussion on たい in issue #16 where I laid out my thoughts for future conjugation forms in this comment: https://github.com/baileysnyder/japanese-conjugation/issues/16#issuecomment-1716578354

Basically, it makes sense to add more conjugation types, it would just take a decent amount of work to implement. I was specifically feeling volitional, potential, passive, and causitive.

Since I think the best version of this app would have more conjugation types, I think we should leave this issue open.

**Comment by baileysnyder** [comment]
I've created an issue for volitional (#31) and another issue for passive, causative, potential, and imperative (#32). Since these are the only other forms I plan to add for now, I'm going to mark this issue as closed.
