### ISSUE TITLE
Show all valid answers

### ISSUE THREAD

**Issue by Kaerum** [baileysnyder/japanese-conjugation#5]
Instead of showing only one of the possible answers, show all of them.

Ie.
美味しい conjugated to negative past polite

美味しくなかったです
美味しくありませんでした

**Comment by baileysnyder** [comment]
My thinking is that since most of the alternative conjugations are so rare (I'm not sure I've ever seen くありませんでした in the wild) it wouldn't be worth it. The worst case would show じゃないです, ではないです, じゃありません, ではありません all at once which I think would needlessly overwhelm a beginner. I think for someone just starting it's better to focus on the conjugation most widely used and then later along when they understand ない=ありません and じゃ=では the alternative conjugations are easy to pick up.
